######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 04:51:40 2013
######################################################################

QMAKE_CXXFLAGS += -std=c++11
QT += core gui xml
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baseboggleplayer.h boggleboard.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += boggleboard.cpp boggleplayer.cpp main.cpp mainwindow.cpp
