#!/bin/bash

# log_msg() function
# input: (STATUS, COLOR, MSG)
# output: colored status in the same line with MSG
#===========================================================================#

log_msg() {

    STATUS=$1
    # tput setaf colors
    case $2 in
        BLACK ) COLOR=0
            ;;
        RED ) COLOR=1
            ;;
        GREEN ) COLOR=2
            ;;
        YELLOW ) COLOR=3
            ;;
        BLUE ) COLOR=4
            ;;
        MAGENTA ) COLOR=5
            ;;
        CYAN ) COLOR=6
            ;;
        WHITE ) COLOR=7
            ;;
    esac
    MSG=$3

    MAXCOL=70                   # MAXCOL=$(tput cols)
    OFFSET=4                    # This is for '<' or '<<<'
    NORMAL=$(tput sgr0)         # Normal color mode
    COLORSTATUS="$(tput setaf $COLOR)${STATUS}$NORMAL"

    let COL=$MAXCOL+${#COLORSTATUS}-$OFFSET-${#MSG}-${#STATUS}
    # tput cols = terminal width
    # 3 = <<<
    # MSG = $1
    # STATUS = text
    # COLORSTATUS = wrapped text

    if [[ ${#MSG} -ge ${COL} ]] 
        # if MSG length too long, then print in new line
    then
        let COLFORLONG=$MAXCOL+${#COLORSTATUS}-$OFFSET-${#STATUS}
        # new line, need a new COL, i.e. ${#MSG} = 0
        printf "\n%${COLFORLONG}s"  "$COLORSTATUS"
    else
        printf "%${COL}s"  "$COLORSTATUS"
    fi
}
